{% set name = "sarpyx" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # TODO: replace with release tarball URL + sha256 for conda-forge.
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - python >=3.11,<3.13
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.11,<3.13
    - matplotlib
    - scipy
    - geopandas >=1.1.1
    - shapely
    - numpy
    - openpyxl
    - h5py
    - numba
    - jupyter
    - rasterio >=1.4.3
    - zarr >=3.0.0
    - joblib >=1.5.1
    - dask >=2025.5.1
    - lxml >=5.4.0
    - huggingface-hub >=0.34.1
    - tifffile >=2025.6.11
    - folium >=0.20.0
    - plotly >=6.2.0
    - lightning >=2.5.3
    - einops >=0.8.1
    - opt-einsum >=3.4.0
    - scikit-image >=0.25.2
    - pykeops >=2.3
    - kornia >=0.8.1
    - tensorboard >=2.20.0
    - tensorboardx >=2.6.4
    - wandb >=0.21.3
    - scikit-learn >=1.7.2
    - geographiclib >=2.1
    - python-dotenv >=0.9.9
    - pyarrow >=23.0.0
    - fastparquet >=2025.12.0

test:
  imports:
    - sarpyx
  commands:
    - sarpyx --help

about:
  summary: A swissknife for SAR processing.
  home: https://github.com/sirbastiano/srp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sirbastiano
