# Configuration for Real-Valued Transformer with Compression Architecture  
# Aligned with successful SSM configuration pattern

# Data directory
data_dir: "/Data/sar_focusing"

# Model configuration (matches successful SSM pattern)
model:
  name: "rv_transformer"
  input_dim: 4              # Real/imag + position channels (matches actual data)
  model_dim: 64             # Matches successful SSM model_dim
  num_layers: 4             # Same as successful SSM
  num_heads: 8              # Reasonable for model_dim=64
  ff_dim: 256               # 4x model_dim (standard transformer ratio)
  dropout: 0.1              # Same as SSM
  mode: "parallel"          # Same as SSM
  max_seq_len: 1000         # Match patch_size sequence length
  compression_ratio: 0.1    # Creates "tiny embeddings" like SSM
  verbose: false

# Training configuration (matches successful SSM training)
training:
  patience: 20              # Same as successful SSM
  delta: 0.00001            # Same as successful SSM
  weight_decay: 0.001       # Same as successful SSM
  epochs: 80                # Same as successful SSM
  lr: 0.0001                # Same as successful SSM
  scheduler_type: "cosine"  # Same as successful SSM
  loss_fn: "polarimetric"          
  save_dir: "./results/rv_transformer_compression"
  mode: "parallel"          # Same as successful SSM
  warmup_epochs: 3          # Same as successful SSM
  warmup_start_lr: 0.00001  # Same as successful SSM
  
  # Enhanced training options
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  
  # WandB configuration
  wandb_project: "ssm4sar"
  wandb_entity: "gabrieledaga01-universit-di-bologna"
  wandb_tags: ["rv_transformer", "compression_architecture", "sar_focusing"]

# Device configuration
device: "cuda"

# Dataloader configuration (EXACTLY matches successful SSM)
dataloader:
  data_dir: "/Data/sar_focusing"
  level_from: "rc"          # Same as successful SSM
  level_to: "az"            # Same as successful SSM
  num_workers: 0
  patch_mode: "rectangular"
  patch_size: [1000, 1]     # SAME as successful SSM - key for row processing!
  buffer: [1000, 1000]      # Same as successful SSM
  stride: [1000, 1]         # Same as successful SSM
  max_base_sample_size: [50000, 50000]  # Same as successful SSM
  shuffle_files: false      # Same as successful SSM
  concatenate_patches: false # Same as successful SSM
  complex_valued: false     # Real-valued transformer uses real data processing
  save_samples: false
  online: true              # Same as successful SSM
  verbose: false
  
  # Split configurations (same as successful SSM)
  train:
    batch_size: 64          # Same as successful SSM
    samples_per_prod: 5000  # Same as successful SSM
    patch_order: "row"      # Same as successful SSM - CRITICAL!
    max_products: 10        # Same as successful SSM
    filters:
      years: [2023]         # Same as successful SSM
  
  validation:
    batch_size: 32          # Same as successful SSM
    samples_per_prod: 500   # Same as successful SSM
    patch_order: "row"      # Same as successful SSM - CRITICAL!
    max_products: 5         # Same as successful SSM
    filters:
      years: [2024]         # Same as successful SSM
  
  test:
    batch_size: 32          # Same as successful SSM
    samples_per_prod: 500   # Same as successful SSM
    patch_order: "row"      # Same as successful SSM
    max_products: 1         # Same as successful SSM
    filters:
      years: [2025]         # Same as successful SSM

  inference:
    batch_size: 32          # Same as successful SSM
    samples_per_prod: 10000 # Same as successful SSM
    patch_order: "row"      # Same as successful SSM
    max_products: 4         # Same as successful SSM
    filters:
      years: [2025]         # Same as successful SSM

# Transform configuration (matches successful SSM)
transforms:
  normalize: true           # Same as successful SSM
  complex_valued: false     # Real-valued processing
  normalization_type: "minmax"  # Same as successful SSM
  rc_min: -6000            # Same as successful SSM
  rc_max: 6000             # Same as successful SSM
  gt_min: -6000            # Same as successful SSM
  gt_max: 6000             # Same as successful SSM