# Configuration for Simple SSM Training

# Data directory
data_dir: "/Data/sar_focusing"

# Training parameters
epochs: 150
batch_size: 32
lr: 1e-4
mode: "column_wise"

# Model configuration
model:
  name: "simple_ssm"
  input_dim: 4  # real, imag, pos_y, pos_x
  state_dim: 128
  output_dim: 2  # real, imag (exclude pos encoding from output)
  num_layers: 6
  dropout: 0.1
  use_pos_encoding: true

# Training configuration
training:
  patience: 20
  delta: 0.0001
  weight_decay: 1e-5

# Base save directory
base_save_dir: "./results/simple_ssm_results"

# Device configuration
device: "cuda"

# Dataloader configuration
dataloader:
  level_from: "rcmc"
  level_to: "az"
  num_workers: 4
  patch_mode: "rectangular"
  patch_size: [1000, 1]  # Vertical columns: height=1000, width=1
  buffer: [1000, 1000]
  stride: [1000, 1]  # Non-overlapping columns
  shuffle_files: true
  complex_valued: false  # Use real-valued representation
  save_samples: false
  backend: "zarr"
  verbose: true
  cache_size: 500
  online: false
  concatenate_patches: false  # Process individual columns
  positional_encoding: true  # Enable positional encoding
  
  # Training split
  train:
    batch_size: 32
    samples_per_prod: 3000
    patch_order: "col"
    max_products: 3
    pattern: "*052337*.zarr"
    
  # Validation split  
  validation:
    batch_size: 32
    samples_per_prod: 1000
    patch_order: "col"
    max_products: 1
    pattern: "*048442*.zarr"
    
  # Test split
  test:
    batch_size: 16
    samples_per_prod: 500
    patch_order: "col"
    max_products: 1
    pattern: "*049667*.zarr"

# Transform configuration
transforms:
  normalize: true
  complex_valued: false
  rc_min: -3000
  rc_max: 3000
  gt_min: -12000
  gt_max: 12000
